import { Document, Scalar } from 'yaml';
import {
  CI_TRIGGERS,
  OPENROUTER_SECRET_NAME,
  PINNED_ACTIONS,
  RESULT_FILENAME,
  RUNNER_BUNDLE_PATH,
  RUN_META_FILENAME,
  type CiTriggerEvent,
} from './constants.js';

/**
 * specs/14-export-to-ci.md (P2, security-critical) — the generated GitHub
 * Actions workflow. Pure: no DB, no HTTP, no LLM, no container (AC-9/AC-25).
 * Every requirement below is individually verifiable against the rendered
 * string; see plans/14-export-to-ci.md's P2 gate for the exact assertions.
 *
 * D11/AC-16 — this file's single hardest invariant: NO agent- or
 * user-authored text (agent name, repo name, system prompt, skill body,
 * memory content, branch name, PR title/body) is EVER interpolated into a
 * `run:` step. The only two `run:` bodies below are fixed constants — the
 * runner invocation and the D-P2 sidecar writer — and every variable value
 * they need arrives through a step-level `env:` block, never string
 * interpolation. `triggers`/`postAs` are the only caller-supplied inputs,
 * and both are re-validated here against closed sets before use — this file
 * never trusts that upstream validation already ran.
 *
 * P-9 — this document is built as a plain object tree and handed to `yaml`'s
 * `Document`/`stringify`, exactly like `manifest.ts` already does for the
 * agent manifest — never `Array.prototype.join('\n')` over hand-quoted
 * strings. A real YAML serializer quotes/escapes whatever a value actually
 * is, so a hostile trigger list or `postAs` value (already re-validated
 * below against a closed set, defence in depth) can never break out of the
 * surrounding YAML structure.
 */

export type PostAsMode = 'github_review' | 'pr_comment' | 'none';

export interface BuildWorkflowInput {
  triggers: readonly string[];
  postAs: PostAsMode;
}

const HEADER_COMMENT =
  ' Generated by DevDigest — export-to-CI (specs/14-export-to-ci.md).\n' +
  ' Edits are safe: re-running "Update CI config" in DevDigest will overwrite\n' +
  ' this file with a fresh generation from the agent\'s current configuration.';

function usesValue(sha: string, repo: string): string {
  return `${repo}@${sha}`;
}

/** Re-validate against the closed trigger set and render in a stable,
 *  deterministic order (AC-9) — never the caller-supplied order. */
function normalizeTriggers(triggers: readonly string[]): CiTriggerEvent[] {
  const requested = new Set(triggers);
  const kept = CI_TRIGGERS.filter((t) => requested.has(t));
  return kept.length > 0 ? kept : [CI_TRIGGERS[0]];
}

/** AC-61 — explicit, minimal `permissions:`. `contents: read` always;
 *  `pull-requests: write` only when the selected publishing mode posts to
 *  the pull request. Nothing beyond `contents: read` for `post_as: 'none'`. */
function permissionsBlock(postAs: PostAsMode): Record<string, string> {
  if (postAs === 'none') {
    return { contents: 'read' };
  }
  return { contents: 'read', 'pull-requests': 'write' };
}

/** AC-11a — the runner's own documented env contract
 *  (`agent-runner/src/index.ts`), supplied in full, nothing omitted. Every
 *  value here is either a CI-provided secret, GitHub Actions context, or
 *  the closed-set `postAs` literal — never agent/user text. */
function runStepEnvBlock(postAs: PostAsMode): Record<string, string> {
  return {
    OPENROUTER_API_KEY: `\${{ secrets.${OPENROUTER_SECRET_NAME} }}`,
    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
    GITHUB_REPOSITORY: '${{ github.repository }}',
    PR_NUMBER: '${{ github.event.pull_request.number }}',
    DEVDIGEST_POST_AS: postAs,
  };
}

/**
 * Build the generated workflow YAML.
 *
 * @throws if `postAs` is not one of the three closed-set literals — a
 *   defensive re-check, never trusting that the caller already validated
 *   `CiExportInput` (this module is pure and has no route context of its own).
 */
export function buildWorkflowYaml(input: BuildWorkflowInput): string {
  if (input.postAs !== 'github_review' && input.postAs !== 'pr_comment' && input.postAs !== 'none') {
    throw new Error(`Invalid post_as value for workflow generation: ${String(input.postAs)}`);
  }
  const triggers = normalizeTriggers(input.triggers);

  const workflow = {
    name: 'DevDigest Review',
    on: {
      pull_request: {
        // D17/AC-60 — `pull_request`, never `pull_request_target`. This
        // trigger never exposes repository secrets to code checked out from
        // a fork.
        types: [...triggers],
      },
    },
    jobs: {
      review: {
        'runs-on': 'ubuntu-latest',
        // AC-60 — the second, independent line of defence: even though
        // `pull_request` already withholds secrets from fork-headed PRs, the
        // job additionally refuses to run for one at all. The runner does
        // NOT guard this itself (`agent-runner/src/context.ts`), so this is
        // the only line of defence.
        if: 'github.event.pull_request.head.repo.fork == false',
        permissions: permissionsBlock(input.postAs),
        steps: [
          {
            name: 'Checkout',
            uses: usesValue(PINNED_ACTIONS.checkout.sha, 'actions/checkout'),
          },
          {
            name: 'Setup Node',
            uses: usesValue(PINNED_ACTIONS.setupNode.sha, 'actions/setup-node'),
            with: { 'node-version': '22' },
          },
          // AC-11/D14 — no `uses: devdigest/review-action@v1`; a real,
          // resolvable invocation of the bundle's own runner entrypoint. No
          // install step — the ncc bundle has no runtime `node_modules`
          // dependency (D14).
          {
            name: 'Run DevDigest review',
            env: runStepEnvBlock(input.postAs),
            run: `node ${RUNNER_BUNDLE_PATH}`,
          },
          // D-P2 — the sidecar the ingest boundary (AC-18) authenticates
          // against. `if: always()` so it is written even when the run step
          // above exits non-zero (a triggered gate). Every value is read
          // from `process.env` at RUNTIME, set via this step's own `env:`
          // block from GitHub Actions context — never interpolated into the
          // run string itself (AC-16).
          {
            name: 'Write run metadata',
            if: 'always()',
            env: {
              DEVDIGEST_COMMIT_SHA: '${{ github.event.pull_request.head.sha }}',
              DEVDIGEST_REPOSITORY: '${{ github.repository }}',
              DEVDIGEST_PR_NUMBER: '${{ github.event.pull_request.number }}',
            },
            run: `node -e "const fs=require('fs');fs.writeFileSync('${RUN_META_FILENAME}',JSON.stringify({commit_sha:process.env.DEVDIGEST_COMMIT_SHA,repository:process.env.DEVDIGEST_REPOSITORY,pr_number:Number(process.env.DEVDIGEST_PR_NUMBER)}));"`,
          },
          // AC-11b — published even on a gate-triggered non-zero exit, so
          // ingestion always has something to retrieve; `if-no-files-found:
          // warn` (never `error`) so a hard-failed run (AC-21, no artifact
          // at all) still completes the upload step instead of failing the
          // whole job on top of the review failure.
          {
            name: 'Upload result artifact',
            if: 'always()',
            uses: usesValue(PINNED_ACTIONS.uploadArtifact.sha, 'actions/upload-artifact'),
            with: {
              name: 'devdigest-result',
              // Trailing `\n` so `yaml` picks the block-literal "clip"
              // chomping indicator (`|`, one trailing newline kept) — the
              // exact style the previous hand-rolled `path: |` block used.
              path: `${RESULT_FILENAME}\n${RUN_META_FILENAME}\n`,
              'if-no-files-found': 'warn',
            },
          },
        ],
      },
    },
  };

  const doc = new Document(workflow);
  doc.commentBefore = HEADER_COMMENT;

  // AC-62 — attach the resolved-tag version as a genuine YAML comment (never
  // part of the `uses:` string value itself, which must stay an exact,
  // resolvable `owner/repo@<sha>` ref) via the library's own comment API —
  // never string concatenation.
  annotateUsesComment(doc, ['jobs', 'review', 'steps', 0, 'uses'], PINNED_ACTIONS.checkout.version);
  annotateUsesComment(doc, ['jobs', 'review', 'steps', 1, 'uses'], PINNED_ACTIONS.setupNode.version);
  annotateUsesComment(
    doc,
    ['jobs', 'review', 'steps', 4, 'uses'],
    PINNED_ACTIONS.uploadArtifact.version,
  );

  // `lineWidth: 0` disables the library's automatic line-folding — every
  // scalar (notably the "Write run metadata" step's `run:` command) renders
  // on a single line, exactly as the previous hand-rolled implementation
  // emitted it. Folding is a cosmetic YAML-serialization choice; disabling
  // it avoids any doubt about a folded plain scalar's re-parsed value.
  return doc.toString({ lineWidth: 0 });
}

function annotateUsesComment(doc: Document, path: (string | number)[], version: string): void {
  const node = doc.getIn(path, true);
  if (node instanceof Scalar) {
    node.comment = ` ${version}`;
  }
}
