import type { CSSProperties } from "react";

/** Co-located styles for the ExportWizard tree. */
export const s = {
  body: { padding: "20px 24px", display: "flex", flexDirection: "column", gap: 18, minHeight: 320 } satisfies CSSProperties,
  stepsBar: { padding: "16px 24px 0" } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 } satisfies CSSProperties,
  footerRight: { display: "flex", gap: 10 } satisfies CSSProperties,
  fieldGroup: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  label: { fontSize: 12.5, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  targetGrid: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  targetCard: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 8,
    border: `1px solid ${active ? "var(--accent)" : "var(--border)"}`,
    background: "var(--bg-elevated)",
    cursor: "pointer",
    textAlign: "left",
  }),
  fileList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 360, overflowY: "auto" } satisfies CSSProperties,
  fileCard: { border: "1px solid var(--border)", borderRadius: 7, overflow: "hidden" } satisfies CSSProperties,
  fileHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  filePre: {
    margin: 0,
    padding: 10,
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    maxHeight: 220,
    overflowY: "auto",
    color: "var(--text-primary)",
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
  checkboxRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13 } satisfies CSSProperties,
  radioRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, padding: "6px 0" } satisfies CSSProperties,
  secretRow: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "6px 0", fontSize: 13 } satisfies CSSProperties,
  guidanceBox: {
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  installCard: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "14px 16px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  installRow: { display: "flex", gap: 12 } satisfies CSSProperties,
  resultBox: {
    padding: "12px 14px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 13,
  } satisfies CSSProperties,
} as const;
