import type { CSSProperties } from "react";

/** Co-located styles for /agent-performance. */
export const s = {
  page: {
    maxWidth: 1200,
    margin: "0 auto",
    padding: "28px 32px 60px",
    display: "flex",
    flexDirection: "column",
    gap: 24,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "flex-start", gap: 16 } satisfies CSSProperties,
  headerText: { flex: 1 } satisfies CSSProperties,
  h1: { fontSize: 22, fontWeight: 700 } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  rangeRow: { display: "flex", gap: 6, alignItems: "center" } satisfies CSSProperties,
  tiles: { display: "flex", gap: 14 } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  cards: { display: "flex", gap: 24, flexWrap: "wrap" } satisfies CSSProperties,
  card: {
    flex: "1 1 320px",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 18,
  } satisfies CSSProperties,
  note: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "8px 10px",
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  thSortBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    padding: 0,
    font: "inherit",
    color: "inherit",
    cursor: "pointer",
  } satisfies CSSProperties,
  td: { padding: "8px 10px", borderBottom: "1px solid var(--border)", color: "var(--text-secondary)" } satisfies CSSProperties,
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  lowSampleChip: {
    display: "inline-block",
    marginLeft: 6,
    padding: "1px 6px",
    borderRadius: 999,
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.02em",
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  expandBtn: {
    background: "none",
    border: "none",
    padding: 2,
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
  } satisfies CSSProperties,
  detailRow: { background: "var(--bg-hover)" } satisfies CSSProperties,
  detailCell: { padding: "10px 10px 14px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  detailGrid: { display: "flex", gap: 24, flexWrap: "wrap", fontSize: 12.5 } satisfies CSSProperties,
  detailLabel: { color: "var(--text-muted)", marginRight: 4 } satisfies CSSProperties,
  provenanceLine: { fontSize: 12, color: "var(--text-muted)", marginTop: 6 } satisfies CSSProperties,
  skeletonTiles: { display: "flex", gap: 14 } satisfies CSSProperties,
  // Gap 2 (plan-verifier fix round) — the avg accept-rate tile's CircularScore
  // treatment, mirrored from StatsTab/styles.ts's own `acceptTile`.
  acceptTile: {
    flex: 1,
    minWidth: 190,
    display: "flex",
    alignItems: "center",
    gap: 14,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 18,
  } satisfies CSSProperties,
  acceptText: { minWidth: 0 } satisfies CSSProperties,
  tileLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
  } satisfies CSSProperties,
  tileValue: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em", marginTop: 8 } satisfies CSSProperties,
} as const;
